use_frameworks!

platform :ios, '8.0'


target 'RACNetWorkTool_Example' do
  pod 'RACNetWorkTool'
  
  pod 'ReactiveCocoa','2.5.0'
  # 网络请求
  pod 'AFNetworking'
  pod 'YYModel'                   
  
end
